rails/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount KomachiHeartbeat::Engine => '/ops'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'branches#index'

  resources :branches, only: %i[index show] do
    collection do
      get :result
    end
  end
  resources :reviews, only: %i[show]
  resources :assessment_requests, only: %i[new create] do
    get :done, on: :collection
  end
  resources :area_filtering, only: %i[create]

  get '/api/:id/cities', to: 'shared_api#cities'
  get '/api/assessment_requests/:id/branches', to: 'assessment_requests#branches'
  # branch_by_name_path(id: 1, company_name: 'speee不動産', branch_name: '目黒店')という名前付きルーティングが使えるようになる branch_nameはオプショナル
  get 'branches/:id/:company_name(/:branch_name)', to: 'branches#show', as: :branch_by_name
end

rails/app/models/branch.rb
# frozen_string_literal: true

class Branch < ApplicationRecord
  belongs_to :company
  belongs_to :city
  has_many :assessable_areas, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :assessable_cities, through: :assessable_areas, source: :city

  validates :post_code, presence: true
  validates :phone_number, presence: true
  validates :fax_number, presence: true
  validates :open_hours, presence: true
  validates :closed_days, presence: true
  validates :catch_copy, presence: true
  validates :introduction, presence: true
  validates :street_address, presence: true
  validates :ieul_branch_id, presence: true, numericality: { only_integer: true }

  def full_name
    company.name + (name || '本店')
  end

  def full_address
    city.prefecture.name + city.name + street_address
  end

  def city_address
    city.prefecture.name + city.name
  end

  def evaluate_value
    if reviews.blank?
      return {
        average_responsiveness_satisfaction: 0,
        normalized_sales_satisfaction: 0,
        normalized_sales_speed: 0
      }
    end
    # evaluate_valueの範囲
    evaluate_min_value = 1
    evaluate_max_value = 5

    # レビューに関連する全体のデータを一度に取得(db依存性がある MySQL用)
    branch_reviews = reviews.select(
      'AVG(company_satisfaction_id) AS average_satisfaction',
      'AVG(contract_price - appraisal_price) AS min_sales_satisfaction_indicator',
      'AVG(DATEDIFF(sale_period, listing_period)) AS min_sales_speed_indicator'
    ).first

    average_responsiveness_satisfaction = branch_reviews.average_satisfaction

    # 売却満足度の指標の正規化
    min_sales_satisfaction = Review.minimum('contract_price - appraisal_price')
    max_sales_satisfaction = Review.maximum('contract_price - appraisal_price')
    # 正規化して0~1にスケール
    normalized_sales_satisfaction = Normalizer.normalize(branch_reviews.min_sales_satisfaction_indicator,
                                                         min_sales_satisfaction, max_sales_satisfaction)
    # 0~1になったものをevaluate_min_value~evaluate_max_valueにスケールする
    normalized_sales_satisfaction = Normalizer.denormalize(normalized_sales_satisfaction, evaluate_min_value,
                                                           evaluate_max_value)
    # 反転させる
    normalized_sales_satisfaction = (evaluate_max_value + evaluate_min_value) - normalized_sales_satisfaction

    # 売却速度に関する指標の正規化
    sales_speed_limits = Review.select(
      "MIN(DATEDIFF(sale_period, listing_period)) AS min_sales_speed,
      MAX(DATEDIFF(sale_period, listing_period)) AS max_sales_speed"
    ).first

    min_sales_speed = sales_speed_limits.min_sales_speed
    max_sales_speed = sales_speed_limits.max_sales_speed
    normalized_sales_speed = Normalizer.normalize(branch_reviews.min_sales_speed_indicator, min_sales_speed,
                                                  max_sales_speed)
    normalized_sales_speed = Normalizer.denormalize(normalized_sales_speed, evaluate_min_value, evaluate_max_value)
    normalized_sales_speed = (evaluate_max_value + evaluate_min_value) - normalized_sales_speed

    {
      average_responsiveness_satisfaction:,
      normalized_sales_satisfaction:,
      normalized_sales_speed:
    }
  end

  def as_json(options = {})
    super(options.merge(methods: :full_name))
  end
end

rails/app/controllers/branches_controller.rb
# frozen_string_literal: true

class BranchesController < ApplicationController
  before_action :set_breadcrumbs

  def index
    load_dependencies
    @branches = @branches.paginate(page: params[:page], per_page: 10)
  end

  def show
    company_name = params[:company_name]
    branch_name = params[:branch_name]

    query = Branch.preload(:company, city: :prefecture, reviews: { city: :prefecture })

    @branch = if branch_name.present?
                query.find_by(name: branch_name)
              elsif company_name.present?
                query.joins(:company).find_by(companies: { name: company_name })
              else
                query.find_by(id: params[:id])
              end

    return render file: Rails.public_path.join('404.html'), status: :not_found, layout: false if @branch.blank?

    evaluate_value = @branch.evaluate_value
    @average_responsiveness_satisfaction = evaluate_value[:average_responsiveness_satisfaction]
    @normalized_sales_satisfaction = evaluate_value[:normalized_sales_satisfaction]
    @normalized_sales_speed = evaluate_value[:normalized_sales_speed]

    add_breadcrumb('店舗一覧', branches_path)
    add_breadcrumb(@branch.full_name)
  end

  def result
    load_dependencies

    redirect_to branches_path and return if invalid_prefecture_id? || invalid_city_id?

    if filtering_by_prefecture?
      # 都道府県まで指定した場合
      filter_branches_by_prefecture
    else
      # 市区町村まで指定した場合
      redirect_to branches_path and return unless City.exists?(id: params[:city_id])

      filter_branches_by_city
    end
  end

  private

  def load_dependencies
    @prefectures = Prefecture.all
    @cities = []
    @area_filtering_form = AreaFilteringForm.new
    @branches = Branch.preload(:company, city: :prefecture, reviews: { city: :prefecture })
  end

  def invalid_prefecture_id?
    params[:prefecture_id].nil? || !numeric?(params[:prefecture_id]) || !Prefecture.exists?(id: params[:prefecture_id])
  end

  def invalid_city_id?
    params[:city_id].nil? || !numeric?(params[:city_id])
  end

  def filtering_by_prefecture?
    params[:city_id].present? && params[:city_id].to_i.zero?
  end

  def filter_branches_by_prefecture
    @branches = @branches.joins(:city).where(cities: { prefecture_id: params[:prefecture_id] })
    @branches_per_page = @branches.paginate(page: params[:page], per_page: 10)
    @branch_address = Prefecture.find_by(id: params[:prefecture_id])&.name
  end

  def filter_branches_by_city
    @branches = @branches.where(city_id: params[:city_id]) if params[:city_id].present?
    @branches_per_page = @branches.paginate(page: params[:page], per_page: 10)
    @city = City.find_by(id: params[:city_id])
    @branch_address = @city.city_address if @city.present?
  end

  def numeric?(string)
    string.match?(/\A-?\d+(\.\d+)?\z/)
  end

  def add_breadcrumb(label, path = nil)
    @breadcrumbs << { label:, path: }
  end

  def set_breadcrumbs
    @breadcrumbs = []
  end
end

rails/app/helpers/branches_helper.rb
# frozen_string_literal: true

module BranchesHelper
end

rails/app/views/branches/_area_filtering_form.erb
<h3 class="mb-4">店舗を検索する</h3>
<div>
    <%=
        form_with(
            model: area_filtering_form,
            url: area_filtering_index_path,
            local: true,
            data: {
                controller: "area-filtering-form"
            }
        ) do |form|
    %>

    <div class="mb-3">
        <%= form.label :prefecture_id, "都道府県" %>
        <%=
        form.collection_select(
            :prefecture_id,
            prefectures,
            :id,
            :name,
            {
                prompt: "都道府県を選択してください",
                required: true
            },
            {
                class: "form-select", 
                data: {
                    area_filtering_form_target: "prefectureId",
                    action: "change->area-filtering-form#updateCities"
                }
            }
        )
        %>
    </div>

    <div class="mb-3">
        <%= form.label :city_id, "市区町村" %>
        <%=
            form.collection_select(
                :city_id,
                cities,
                :id,
                :name,
                {
                    prompt: "市区町村を選択してください",
                    required: true
                },
                {
                    class: "form-select", 
                    data: {
                        area_filtering_form_target: "cityId"
                    }
                }
            )
        %>
    </div>

    <div class="mb-3">
        <%=
        form.submit(
            "店舗を検索する",
            {
            class: "btn btn-primary",
            data: {
                assessment_request_form_target: "submitButton"
            }
            }
        )
        %>
    </div>
    <% end %>
</div>

rails/app/views/branches/_branch.html.erb
<div class="mb-4">
    <div class="card" style="border: 1px solid #ddd;">
        <div class="row">
            <div class="col-md-3 text-center">
                <h4 class="card-title mt-4">
                    <%= link_to branch.full_name,
                                branch_by_name_path(id: branch.id, company_name: branch.company.name,
                                                    branch_name: branch.name),
                                data: { 'turbolinks' => false } %>
                </h4>
                <p class="card-text" style="font-size: 24px;">★
                    <%= branch.reviews.present? ? branch.reviews.average(:company_satisfaction_id).round(1) : '-' %>
                </p>
                <img src="<%= branch.company.logo_url %>" class="img-fluid" alt="<%= branch.company.name %>のロゴ画像">
            </div>
            <div class="card-body col-md-9">
                <p class="card-text"><strong>営業時間：</strong><%= branch.open_hours %></p>
                <p class="card-text"><strong>定休日：</strong><%= branch.closed_days %></p>
                <p class="card-text"><strong>住所：</strong><%= branch.full_address %></p>
                <% if branch.reviews.present? %>
                    <p class="card-text"><strong>会社の決め手：</strong><%= branch.reviews.first.chosen_company_reason %></p>
                <% end %>
            </div>
        </div>
    </div>
</div>

rails/app/views/branches/_radar_chart.html.erb
<canvas id="review-radar-chart"></canvas>
<script>
window.addEventListener('turbo:load', () => {

    const review_radar_chart = document.getElementById('review-radar-chart');

    if (review_radar_chart != null) {
        const ctx = review_radar_chart.getContext('2d');
        const average_correspond_satisfaction = parseFloat("<%= average_responsiveness_satisfaction %>");
        const normalized_sales_value = parseFloat("<%= normalized_sales_satisfaction %>");
        const normalized_sale_data_value = parseFloat("<%= normalized_sales_speed %>");

        // すでにチャートが存在している場合は削除する
        if (Chart.getChart(ctx)) {
            Chart.getChart(ctx).destroy();
        }

        new Chart(ctx, {
            type: 'radar',
            data: {
                labels: ['対応満足度', '売却価格', '売却スピード'],
                datasets: [{
                    data: [average_correspond_satisfaction, normalized_sales_value, normalized_sale_data_value],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                    ],
                    borderWidth: 1
                }],
            },
            options: {
                plugins: {
                    legend: {
                        display: false, // 凡例を非表示にする
                    }
                },
                scales: {
                    r: {
                        pointLabels: {
                            font: {
                                size: 13
                            }
                        },
                        angleLines: {
                            display: true // 角度線の表示
                        },
                        min: 0, // 最小値
                        max: 5, // 最大値
                        suggestedMin: 0,
                        suggestedMax: 5,
                        ticks: {
                            stepSize: 1,
                        }
                    },
                }
            }
        });
    }
}, { once: true });
</script>

rails/app/views/branches/_review.html.erb
<div class="mb-3 p-3 border rounded">
  <div class="fw-bold"><%= link_to review.headline, review_path(id: review.id) %> : ★<%= review.company_satisfaction_id %></div>
  <div class="mb-2"><%= review.company_satisfaction_reason %></div>
  <div>
    成約価格 : <%= review.contract_price / 10_000 %>万円
    （<%= review.city.prefecture.name %><%= review.city.name %>・<%= review.sale_period.strftime('%Y年%m月') %>に売却）
  </div>
</div>

rails/app/views/branches/index.html.erb
<% provide(:title, '店舗一覧') %>
<div class="m-4">
  <%= render partial: 'area_filtering_form',
             locals: { area_filtering_form: @area_filtering_form, prefectures: @prefectures,
                       cities: @cities } %>
  <h3 class="my-4">店舗一覧</h3>
  <div class="row">
    <% @branches.each do |branch| %>
      <%= render branch %>
    <% end %>
  </div>
</div>
<%= will_paginate previous_label: '前へ', next_label: '次へ', inner_window: 2 %>

rails/app/views/branches/result.html.erb
<% provide(:title, "#{@branch_address}の不動産会社") %>
<h3>検索結果</h3>

<%= render partial: 'branches/area_filtering_form',
           locals: { area_filtering_form: @area_filtering_form, prefectures: @prefectures, cities: @cities } %>

<h3 class="my-4"><%= @branch_address %>の査定を出せる店舗一覧</h3>

<% if @branches_per_page.any? %>
    <div class="row">
        <% @branches_per_page.each do |branch| %>
        <%= render partial: 'branches/branch', locals: { branch: } %>
        <% end %>
    </div>
    <%= will_paginate @branches_per_page, previous_label: '前へ', next_label: '次へ' %>
<% else %>
    <p>該当する店舗はありません。</p>
<% end %>
<%= link_to '店舗一覧に戻る', branches_path, class: 'btn btn-primary' %>

rails/app/views/branches/show.html.erb
<% provide(:title, @branch.full_name) %>
<div class="container my-4">
  <h1 class="mb-4">
    <%= @branch.full_name %>
  </h1>

  <div class="row">
    <div class="col-md-2">
      <img src="<%= @branch.company.logo_url %>" class="img-fluid" alt="<%= @branch.company.name %>のロゴ画像">
    </div>
    <div class="col-md-10">
        <div class="mb-4">
          <strong>キャッチコピー:</strong> <span class="d-block"><%= @branch.catch_copy %></span>
        </div>
        <div class="mb-4">
          <strong>紹介文:</strong> <span class="d-block"><%= @branch.introduction %></span>
        </div>
    </div>
  </div>

  <div class="row mt-3 mb-3 mr-4">
    <div class="col-md-4">
      <%= render partial: 'radar_chart',
                 locals: { average_responsiveness_satisfaction: @average_responsiveness_satisfaction,
                           normalized_sales_satisfaction: @normalized_sales_satisfaction,
                           normalized_sales_speed: @normalized_sales_speed } %>
    </div>
    <div class="col-md-7 ms-auto">
      <div class="branch-info mt-5">
        <h2 class="h5 fw-bold mb-4"><%= @branch.full_name %>について</h2>
          <div class="d-grid gap-2 ms-auto">
            <div><strong>企業名 :</strong> <%= @branch.company.name %></div>
            <div><strong>郵便番号 :</strong> <%= @branch.post_code %></div>
            <div><strong>住所 :</strong> <%= @branch.full_address %></div>
            <div><strong>電話番号 :</strong> <%= @branch.phone_number %></div>
            <div><strong>FAX :</strong> <%= @branch.fax_number %></div>
            <div><strong>営業時間 :</strong> <%= @branch.open_hours %></div>
            <div><strong>定休日 :</strong> <%= @branch.closed_days %></div>
          </div>
      </div>
    </div>
  </div>

  <div class="reviews mb-4">
    <h2 class="h5 fw-bold"><%= @branch.company.name %>で売却したひとの不動産会社についての口コミ
    （平均評価 <%= @branch.reviews.present? ? @average_responsiveness_satisfaction : '-' %>）</h2>
    <hr>
    <% if @branch.reviews.any? %>
      <% @branch.reviews.each do |review| %>
        <%= render partial: 'review', locals: { review: } %>
      <% end %>
    <% else %>
      <p>表示する口コミはありません。</p>
    <% end %>
  </div>

<div class="text-center mb-4">
    <%= link_to '査定依頼をする', new_assessment_request_path(from: 'branch_show', branch_id: @branch.id),
                class: 'btn btn-primary' %>
</div>
</div>