rails/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount KomachiHeartbeat::Engine => '/ops'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'branches#index'

  resources :branches, only: %i[index show] do
    collection do
      get :result
    end
  end
  resources :reviews, only: %i[show]
  resources :assessment_requests, only: %i[new create] do
    get :done, on: :collection
  end
  resources :area_filtering, only: %i[create]

  get '/api/:id/cities', to: 'shared_api#cities'
  get '/api/assessment_requests/:id/branches', to: 'assessment_requests#branches'
  # branch_by_name_path(id: 1, company_name: 'speee不動産', branch_name: '目黒店')という名前付きルーティングが使えるようになる branch_nameはオプショナル
  get 'branches/:id/:company_name(/:branch_name)', to: 'branches#show', as: :branch_by_name
end

rails/app/controllers/assessment_requests_controller.rb
# frozen_string_literal: true

require 'net/http'
require 'uri'
require 'json'

class AssessmentRequestsController < ApplicationController
  skip_forgery_protection

  IEUL_API_BASE_URL = 'https://miniul-api.herokuapp.com/affiliate/v2'
  URL_PARAM = 'beteran-sumai'

  def new
    @assessment_request_form = AssessmentRequestForm.new

    @prefectures = Prefecture.all
    @cities = []
    @branches = []

    branch_id = params[:branch_id]

    return if branch_id.blank?

    branch = Branch.preload(city: :prefecture).find_by(id: branch_id)
    @assessment_request_form = AssessmentRequestForm.new(
      property_prefecture_id: branch.city.prefecture.id,
      property_city_id: branch.city.id,
      branch_id:
    )
    @cities = [branch.city]
    @branches = [branch]
  end

  def create
    @assessment_request_form = AssessmentRequestForm.new(assessment_request_params)
    @assessment_request_form.url_param = URL_PARAM

    @prefectures = Prefecture.all
    @cities = []
    @branches = []

    if @assessment_request_form.valid?
      # TODO: イエウールのAPIを叩いて査定依頼を送信する
      # TODO: 名前とふりがなを空白で結合
      response = send_assessment_request(@assessment_request_form)

      if response.is_a?(Net::HTTPSuccess)
        redirect_to action: :done, status: :see_other
      else
        render :new, status: :unprocessable_entity
      end
    else
      # Turboの仕様により422を返す必要がある
      render :new, status: :unprocessable_entity
    end
  end

  def done; end

  def branches
    @city = City.find_by(id: params[:id])
    return unless @city

    @branches = @city.branches

    respond_to do |format|
      format.json { render json: @branches }
    end
  end

  private

  def assessment_request_params
    params
      .require(:assessment_request_form)
      .permit(
        :user_first_name,
        :user_last_name,
        :user_first_name_kana,
        :user_last_name_kana,
        :user_tel,
        :user_email,
        :property_city_id,
        :property_address,
        :property_type,
        :property_exclusive_area,
        :property_land_area,
        :property_building_area,
        :property_building_area_unit,
        :property_floor_area,
        :property_room_plan,
        :property_constructed_year,
        :property_prefecture_id,
        :branch_id
      )
  end

  def send_assessment_request(form)
    # 名前とふりがなを空白で結合
    user_name = "#{form.user_last_name} #{form.user_first_name}"
    user_name_kana = "#{form.user_last_name_kana} #{form.user_first_name_kana}"

    uri = URI.parse("#{IEUL_API_BASE_URL}/conversions")
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = uri.scheme == 'https'

    request = Net::HTTP::Post.new(uri.request_uri, { 'Content-Type' => 'application/json' })
    request.body = {
      branch_id: form.branch_id,
      property_city: form.property_city_id,
      property_address: form.property_address,
      property_type: form.property_type,
      property_exclusive_area: form.property_exclusive_area,
      property_land_area: form.property_land_area,
      property_building_area: form.property_building_area,
      property_building_area_unit: form.property_building_area_unit,
      property_floor_area: form.property_floor_area,
      url_param: URL_PARAM,
      property_room_plan: form.property_room_plan,
      property_constructed_year: form.property_constructed_year,
      user_email: form.user_email,
      user_name:,
      user_name_kana:,
      user_tel: form.user_tel
    }.to_json

    http.request(request)
  end
end

rails/app/helpers/assessment_requests_helper.rb
# frozen_string_literal: true

module AssessmentRequestsHelper
end

rails/app/views/assessment_requests/done.html.erb
<div class="card">
    <div class="card-body text-center">
        <h1 class="card-title">お問い合わせありがとうございました</h1>
        <p class="card-text">査定依頼ありがとうございます。</p>
        <p class="card-text">不動産会社からのご連絡をお待ちください。</p>
        <div class="mt-4">
        <%= link_to '店舗一覧に戻る', branches_path, class: 'btn btn-primary mx-2' %>
        <%= link_to 'お問い合わせフォームに戻る', new_assessment_request_path, class: 'btn btn-outline-info mx-2' %>
        </div>
    </div>
</div>

rails/app/views/assessment_requests/new.html.erb
<% provide(:title, '査定依頼フォーム') %>
<h2>査定依頼フォーム</h2>

<% if @assessment_request_form.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @assessment_request_form.errors.to_hash(true).each do |attribute, messages| %>
        <li><%= messages.first %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(
      model: @assessment_request_form,
      url: assessment_requests_path,
      local: true,
      data: {
        controller: 'assessment-request-form',
        action: 'input->assessment-request-form#switchSubmitButtonState'
      }
    ) do |form| %>
  <!-- イエウールの店舗IDを隠しフィールドとして渡す -->
  <!-- チュートリアルの第12章を参照 -->

  <div class="row">
    <span>お名前</span>
    <div class="col-md-6">
    <%= form.text_field(
          :user_last_name,
          placeholder: '田中',
          required: true,
          class: 'form-control custom-placeholder',
          data: {
            assessment_request_form_target: 'userLastName',
            action: 'input->assessment-request-form#validateUserLastName'
          }
        ) %>
    </div>
    <div class="col-md-6">
      <%= form.text_field(
            :user_first_name,
            placeholder: '太郎',
            required: true,
            class: 'form-control custom-placeholder',
            data: {
              assessment_request_form_target: 'userFirstName',
              action: 'input->assessment-request-form#validateUserFirstName'
            }
          ) %>
    </div>
    <p>
      <div data-assessment-request-form-target="userLastNameErrorMessage" class="text-danger"></div>
      <div data-assessment-request-form-target="userFirstNameErrorMessage" class="text-danger"></div>
    </p>
  </div>

  <div class="row">
    <span>フリガナ</span>
    <div class="col-md-6">
      <%= form.text_field(
            :user_last_name_kana,
            {
              placeholder: 'タナカ',
              required: true,
              class: 'form-control custom-placeholder',
              data: {
                assessment_request_form_target: 'userLastNameKana',
                action: 'input->assessment-request-form#validateUserLastNameKana'
              }
            }
          ) %>
    </div>
    <div class="col-md-6">
      <%= form.text_field(
            :user_first_name_kana,
            {
              placeholder: 'タロウ',
              class: 'form-control custom-placeholder',
              data: {
                assessment_request_form_target: 'userFirstNameKana',
                action: 'input->assessment-request-form#validateUserFirstNameKana'
              }
            }
          ) %>
    </div>
    <p>
      <div data-assessment-request-form-target="userLastNameKanaErrorMessage" class="text-danger"></div>
      <div data-assessment-request-form-target="userFirstNameKanaErrorMessage" class="text-danger"></div>
    </p>
  </div>

  <div class="mb-3">
    <%= form.label :user_tel, '電話番号' %>
    <%= form.telephone_field(
          :user_tel,
          {
            placeholder: '09012345678',
            required: true,
            class: 'form-control custom-placeholder',
            data: {
              assessment_request_form_target: 'userTel',
              action: 'input->assessment-request-form#validateUserTel'
            }
          }
        ) %>
    <div data-assessment-request-form-target="userTelErrorMessage" class="text-danger"></div>
  </div>

  <div class="mb-3">
    <%= form.label :user_email, 'メールアドレス' %>
    <%= form.email_field(
          :user_email,
          {
            placeholder: 'test@example.jp',
            required: true,
            class: 'form-control custom-placeholder',
            data: {
              assessment_request_form_target: 'userEmail',
              action: 'input->assessment-request-form#validateUserEmail'
            }
          }
        ) %>
    <div data-assessment-request-form-target="userEmailErrorMessage" class="text-danger"></div>
  </div>

  <div class="mb-3">
    <%= form.label :property_prefecture_id, '物件の都道府県' %>
    <%= form.collection_select(
          :property_prefecture_id,
          @prefectures,
          :id,
          :name,
          {
            prompt: '都道府県を選択してください',
            selected: @assessment_request_form.property_prefecture_id,
            required: true
          },
          {
            class: 'form-select',
            data: {
              assessment_request_form_target: 'propertyPrefectureId',
              action: 'change->assessment-request-form#updateCities'
            }
          }
        ) %>
  </div>

  <div class="mb-3">
    <%= form.label :property_city_id, '物件の市区町村' %>
    <%= form.collection_select(
          :property_city_id,
          @cities,
          :id,
          :name,
          {
            prompt: '市区町村を選択してください',
            selected: @assessment_request_form.property_city_id,
            required: true
          },
          {
            class: 'form-select',
            data: {
              assessment_request_form_target: 'propertyCityId',
              action: 'change->assessment-request-form#updateBranches'
            }
          }
        ) %>
  </div>

  <div class="mb-3">
    <%= form.label :branch_id, '査定依頼を行う店舗' %>
    <%= form.collection_select(
          :branch_id,
          @branches,
          :id,
          :full_name,
          {
            prompt: '店舗を選択してください',
            selected: @assessment_request_form.branch_id,
            required: true
          },
          {
            class: 'form-select',
            data: {
              assessment_request_form_target: 'propertyBranchId'
            }
          }
        ) %>
  </div>

  <div class="mb-3">
    <%= form.label :property_address, '物件の住所' %>
    <%= form.text_field(
          :property_address,
          {
            placeholder: '港区六本木3-2-1',
            required: true,
            class: 'form-control custom-placeholder',
            data: {
              assessment_request_form_target: 'propertyAddress',
              action: 'input->assessment-request-form#validatePropertyAddress'
            }
          }
        ) %>
    <div data-assessment-request-form-target="propertyAddressErrorMessage" class="text-danger"></div>
  </div>

  <div class="mb-3">
    <%= form.label :property_type, '物件種別' %>
    <%= form.select(
          :property_type,
          options_for_select([
                               ['分譲マンション', 1],
                               ['一戸建て', 2],
                               ['土地', 3]
                             ]),
          {
            include_blank: '物件種別を選択してください',
            required: true
          },
          {
            class: 'form-select'
          }
        ) %>
  </div>

    <div class="mb-3">
    <%= form.label :property_building_area_unit, '面積単位' %>
    <div>
      <%= form.select(
            :property_building_area_unit,
            options_for_select([['平方メートル', 1], ['坪', 2]]),
            {
              include_blank: '面積単位を選択してください',
              required: true
            },
            {
              class: 'form-select'
            }
          ) %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :property_exclusive_area, '専有面積' %>
    <%= form.number_field(
          :property_exclusive_area,
          {
            step: 0.01,
            placeholder: 100,
            required: true,
            class: 'form-control custom-placeholder',
            data: {
              assessment_request_form_target: 'propertyExclusiveArea',
              action: 'input->assessment-request-form#validatePropertyExclusiveArea'
            }
          }
        ) %>
    <div data-assessment-request-form-target="propertyExclusiveAreaErrorMessage" class="text-danger"></div>
  </div>

  <div class="mb-3">
    <%= form.label :property_land_area, '土地面積' %>
    <%= form.number_field(
          :property_land_area,
          {
            step: 0.01,
            placeholder: 100,
            required: true,
            class: 'form-control custom-placeholder',
            data: {
              assessment_request_form_target: 'propertyLandArea',
              action: 'input->assessment-request-form#validatePropertyLandArea'
            }
          }
        ) %>
    <div data-assessment-request-form-target="propertyLandAreaErrorMessage" class="text-danger"></div>
  </div>

  <div class="mb-3">
    <%= form.label :property_building_area, '建物面積' %>
    <div>
      <%= form.number_field(
            :property_building_area,
            {
              step: 0.01,
              placeholder: 100,
              required: true,
              class: 'form-control custom-placeholder',
              data: {
                assessment_request_form_target: 'propertyBuildingArea',
                action: 'input->assessment-request-form#validatePropertyBuildingArea'
              }
            }
          ) %>
      <div data-assessment-request-form-target="propertyBuildingAreaErrorMessage" class="text-danger"></div>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :property_floor_area, '延床面積' %>
    <%= form.number_field(
          :property_floor_area,
          {
            step: 0.01,
            placeholder: 100,
            required: true,
            class: 'form-control custom-placeholder',
            data: {
              assessment_request_form_target: 'propertyFloorArea',
              action: 'input->assessment-request-form#validatePropertyFloorArea'
            }
          }
        ) %>
    <div data-assessment-request-form-target="propertyFloorAreaErrorMessage" class="text-danger"></div>
  </div>

  <div class="mb-3">
    <%= form.label :property_room_plan, '間取り' %>
    <%= form.select(
          :property_room_plan,
          options_for_select(
            [
              ['1R(ワンルーム)', 1],
              ['1K / 1DK', 2],
              ['1LK / 1LDK', 3],
              ['2K / 2DK', 4],
              ['2LK / 2LDK', 5],
              ['3K / 3DK', 6],
              ['3LK / 3LDK', 7],
              ['4K / 4DK', 8],
              ['4LK / 4LDK', 9],
              ['5K / 5DK', 10],
              ['5LK / 5LDK', 11],
              ['6K / 6DK', 12],
              ['6LK / 6LDK以上', 13]
            ]
          ),
          {
            include_blank: '間取りを選択してください',
            required: true
          },
          {
            class: 'form-select'
          }
        ) %>
    <div data-assessment-request-form-target="propertyRoomPlanErrorMessage" class="text-danger"></div>
  </div>

  <div class="mb-3">
    <%= form.label :property_constructed_year, '築年数' %>
    <%= form.number_field(
          :property_constructed_year,
          {
            placeholder: '2016',
            in: 1925..2016,
            required: true,
            class: 'form-control custom-placeholder',
            data: {
              assessment_request_form_target: 'propertyConstructedYear',
              action: 'input->assessment-request-form#validatePropertyConstructedYear'
            }
          }
        ) %>
    <div data-assessment-request-form-target="propertyConstructedYearErrorMessage" class="text-danger"></div>
  </div>

  <div class="mb-3">
    <%= form.submit(
          '査定依頼を送信する',
          {
            disabled: true,
            class: 'btn btn-primary',
            data: {
              assessment_request_form_target: 'submitButton'
            }
          }
        ) %>
  </div>

  <%= debug(params) if Rails.env.development? %>
<% end %>